import reflex as rx
from pydantic_settings import BaseSettings
from typing import List, Dict, Any


class AppSettings(BaseSettings):
    APP_NAME: str = "Wellness Dashboard"
    DEFAULT_USER: str = "Wellness Enthusiast"
    COLOR_MAP: Dict[str, Dict[str, str]] = {
        "red": {
            "text": "text-red-600",
            "bg": "bg-red-100",
            "border": "border-red-500",
            "base": "#EF4444",
            "progress_bg": "bg-red-500",
        },
        "blue": {
            "text": "text-blue-600",
            "bg": "bg-blue-100",
            "border": "border-blue-500",
            "base": "#3B82F6",
            "progress_bg": "bg-blue-500",
        },
        "green": {
            "text": "text-green-600",
            "bg": "bg-green-100",
            "border": "border-green-500",
            "base": "#10B981",
            "progress_bg": "bg-green-500",
        },
        "yellow": {
            "text": "text-yellow-600",
            "bg": "bg-yellow-100",
            "border": "border-yellow-500",
            "base": "#F59E0B",
            "progress_bg": "bg-yellow-500",
        },
        "purple": {
            "text": "text-purple-600",
            "bg": "bg-purple-100",
            "border": "border-purple-500",
            "base": "#8B5CF6",
            "progress_bg": "bg-purple-500",
        },
        "pink": {
            "text": "text-pink-600",
            "bg": "bg-pink-100",
            "border": "border-pink-500",
            "base": "#EC4899",
            "progress_bg": "bg-pink-500",
        },
        "gray": {
            "text": "text-gray-600",
            "bg": "bg-gray-100",
            "border": "border-gray-500",
            "base": "#6B7280",
            "progress_bg": "bg-gray-500",
        },
        "teal": {
            "text": "text-teal-600",
            "bg": "bg-teal-100",
            "border": "border-teal-500",
            "base": "#14B8A6",
            "progress_bg": "bg-teal-500",
        },
        "orange": {
            "text": "text-orange-600",
            "bg": "bg-orange-100",
            "border": "border-orange-500",
            "base": "#F97316",
            "progress_bg": "bg-orange-500",
        },
        "cyan": {
            "text": "text-cyan-600",
            "bg": "bg-cyan-100",
            "border": "border-cyan-500",
            "base": "#06B6D4",
            "progress_bg": "bg-cyan-500",
        },
    }
    DEFAULT_COLOR_KEY: str = "gray"
    ICONS_LIST: List[str] = [
        "box",
        "armchair",
        "basketball",
        "cactus",
        "bar-chart",
        "gamepad-2",
        "graduation-cap",
        "music-2",
        "palette",
        "leaf",
        "shopping-bag",
        "terminal-square",
        "home",
        "plane-takeoff",
        "book-open",
        "briefcase",
        "coffee",
        "film",
        "gift",
        "globe",
        "activity",
        "moon",
        "puzzle",
        "rocket",
        "shield-check",
        "headphones",
        "dollar-sign",
        "award",
        "anchor",
        "aperture",
        "camera",
        "cpu",
        "database",
        "disc",
        "feather",
        "filter",
        "flag",
        "git-branch",
        "grid",
        "hard-drive",
        "hash",
        "key",
        "layers",
        "link",
        "lock",
        "map-pin",
        "mic",
        "mouse-pointer",
        "package",
        "paperclip",
        "pen-tool",
        "power",
        "printer",
        "save",
        "scissors",
        "search",
        "server",
        "settings",
        "share-2",
        "shield",
        "slash",
        "smartphone",
        "speaker",
        "star",
        "sun",
        "tag",
        "target",
        "tool",
        "trash-2",
        "trending-up",
        "truck",
        "tv",
        "type",
        "umbrella",
        "unlock",
        "upload-cloud",
        "user",
        "video",
        "volume-2",
        "watch",
        "wifi",
        "wind",
        "zap",
        "zoom-in",
        "activity",
        "alert-circle",
        "archive",
        "at-sign",
        "bar-chart-2",
        "battery-charging",
        "bell",
        "bluetooth",
        "book",
        "bookmark",
        "box",
        "calendar",
        "check-square",
        "chevron-down",
        "chevron-left",
        "chevron-right",
        "chevron-up",
        "clipboard",
        "clock",
        "code",
        "command",
        "compass",
        "copy",
        "crop",
        "crosshair",
        "delete",
        "download-cloud",
        "edit-2",
        "edit-3",
        "external-link",
        "eye-off",
        "facebook",
        "fast-forward",
        "file-minus",
        "file-plus",
        "file-text",
        "film",
        "folder",
        "folder-minus",
        "folder-plus",
        "gift",
        "github",
        "gitlab",
        "globe",
        "layout-grid",
        "hard-drive",
        "heart",
        "help-circle",
        "home",
        "image",
        "inbox",
        "info",
        "instagram",
        "layout",
        "life-buoy",
        "linkedin",
        "loader",
        "log-in",
        "log-out",
        "mail",
        "map",
        "maximize-2",
        "menu",
        "message-circle",
        "message-square",
        "minimize-2",
        "monitor",
        "more-horizontal",
        "more-vertical",
        "move",
        "music",
        "navigation-2",
        "navigation",
        "octagon",
        "package",
        "pause-circle",
        "percent",
        "phone-call",
        "phone-forwarded",
        "phone-incoming",
        "phone-missed",
        "phone-off",
        "phone-outgoing",
        "pie-chart",
        "play-circle",
        "plus-circle",
        "plus-square",
        "pocket",
        "power-off",
        "radio",
        "refresh-ccw",
        "refresh-cw",
        "repeat",
        "rewind",
        "rotate-ccw",
        "rotate-cw",
        "rss",
        "save",
        "send",
        "settings-2",
        "share",
        "shopping-cart",
        "shuffle",
        "sidebar",
        "skip-back",
        "skip-forward",
        "slack",
        "sliders",
        "volume-1",
        "square",
        "stop-circle",
        "tablet",
        "tag",
        "thumbs-down",
        "thumbs-up",
        "toggle-left",
        "toggle-right",
        "trash",
        "trending-down",
        "triangle",
        "twitter",
        "user-check",
        "user-minus",
        "user-plus",
        "user-x",
        "users",
        "video-off",
        "voicemail",
        "volume-1",
        "volume-x",
        "wifi-off",
        "youtube",
        "zap-off",
        "zoom-out",
        "alert-triangle",
        "align-center",
        "align-justify",
        "align-left",
        "align-right",
        "arrow-down-circle",
        "arrow-down-left",
        "arrow-down-right",
        "arrow-down",
        "arrow-left-circle",
        "arrow-left",
        "arrow-right-circle",
        "arrow-right",
        "arrow-up-circle",
        "arrow-up-left",
        "arrow-up-right",
        "arrow-up",
        "award",
        "bold",
        "check-circle",
        "check",
        "chrome",
        "cloud-drizzle",
        "cloud-lightning",
        "cloud-off",
        "cloud-rain",
        "cloud-snow",
        "cloud",
        "codepen",
        "codesandbox",
        "credit-card",
        "crop",
        "divide-circle",
        "divide-square",
        "divide",
        "dollar-sign",
        "download",
        "droplet",
        "edit",
        "eye",
        "figma",
        "file",
        "folder-open",
        "frown",
        "globe-2",
        "italic",
        "link-2",
        "list",
        "meh",
        "minus-circle",
        "minus-square",
        "minus",
        "moon",
        "mouse-pointer-2",
        "paperclip",
        "pause",
        "pen-line",
        "play",
        "plus",
        "shield-off",
        "smile",
        "star-half",
        "sun",
        "terminal",
        "underline",
        "upload",
        "x-circle",
        "x-octagon",
        "x-square",
        "x",
        "flower-2",
        "boom-box",
    ]

    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"


settings = AppSettings()
unique_icons = sorted(list(set(settings.ICONS_LIST)))
valid_lucide_like_icons = []
for icon in unique_icons:
    if (
        icon
        and isinstance(icon, str)
        and (not icon.endswith("-alt"))
        and (" " not in icon)
    ):
        valid_lucide_like_icons.append(
            icon.replace("_", "-")
        )
settings.ICONS_LIST = sorted(
    list(set(valid_lucide_like_icons))
)
if not settings.ICONS_LIST:
    settings.ICONS_LIST = ["box"]