import reflex as rx
from pydantic_settings import BaseSettings
from typing import List, Dict, Any


class AppSettings(BaseSettings):
    APP_NAME: str = "Wellness Dashboard"
    DEFAULT_USER: str = "Wellness Enthusiast"
    COLOR_MAP: Dict[str, Dict[str, str]] = {
        "red": {
            "text": "text-red-600",
            "bg": "bg-red-100",
            "border": "border-red-500",
            "base": "#EF4444",
            "progress_bg": "bg-red-500",
        },
        "blue": {
            "text": "text-blue-600",
            "bg": "bg-blue-100",
            "border": "border-blue-500",
            "base": "#3B82F6",
            "progress_bg": "bg-blue-500",
        },
        "green": {
            "text": "text-green-600",
            "bg": "bg-green-100",
            "border": "border-green-500",
            "base": "#10B981",
            "progress_bg": "bg-green-500",
        },
        "yellow": {
            "text": "text-yellow-600",
            "bg": "bg-yellow-100",
            "border": "border-yellow-500",
            "base": "#F59E0B",
            "progress_bg": "bg-yellow-500",
        },
        "purple": {
            "text": "text-purple-600",
            "bg": "bg-purple-100",
            "border": "border-purple-500",
            "base": "#8B5CF6",
            "progress_bg": "bg-purple-500",
        },
        "pink": {
            "text": "text-pink-600",
            "bg": "bg-pink-100",
            "border": "border-pink-500",
            "base": "#EC4899",
            "progress_bg": "bg-pink-500",
        },
        "gray": {
            "text": "text-gray-600",
            "bg": "bg-gray-100",
            "border": "border-gray-500",
            "base": "#6B7280",
            "progress_bg": "bg-gray-500",
        },
        "teal": {
            "text": "text-teal-600",
            "bg": "bg-teal-100",
            "border": "border-teal-500",
            "base": "#14B8A6",
            "progress_bg": "bg-teal-500",
        },
        "orange": {
            "text": "text-orange-600",
            "bg": "bg-orange-100",
            "border": "border-orange-500",
            "base": "#F97316",
            "progress_bg": "bg-orange-500",
        },
        "cyan": {
            "text": "text-cyan-600",
            "bg": "bg-cyan-100",
            "border": "border-cyan-500",
            "base": "#06B6D4",
            "progress_bg": "bg-cyan-500",
        },
    }
    DEFAULT_COLOR_KEY: str = "gray"
    ICONS_LIST: List[str] = [
        "box_3d_point",
        "armchair",
        "basketball",
        "cactus",
        "chart_bar",
        "gamepad_2",
        "graduation_cap",
        "music_2",
        "palette",
        "plant",
        "shopping_bag",
        "terminal_box",
        "home_smile",
        "flight_takeoff",
        "book_open",
        "briefcase",
        "coffee",
        "film",
        "gift",
        "globe",
        "heart_pulse",
        "moon",
        "puzzle",
        "rocket",
        "shield_check",
        "headphones",
        "dollar_sign",
        "award",
        "anchor",
        "aperture",
        "camera",
        "cpu",
        "database",
        "disc",
        "feather",
        "filter",
        "flag",
        "git_branch",
        "grid",
        "hard_drive",
        "hash",
        "key",
        "layers",
        "link",
        "lock",
        "map_pin",
        "mic",
        "mouse_pointer",
        "package",
        "paperclip",
        "pen_tool",
        "power",
        "printer",
        "save",
        "scissors",
        "search",
        "server",
        "settings",
        "share_2",
        "shield",
        "slash",
        "smartphone",
        "speaker",
        "star",
        "sun",
        "tag",
        "target",
        "tool",
        "trash_2",
        "trending_up",
        "truck",
        "tv",
        "type",
        "umbrella",
        "unlock",
        "upload_cloud",
        "user",
        "video",
        "volume_2",
        "watch",
        "wifi",
        "wind",
        "zap",
        "zoom_in",
        "activity",
        "alert_circle",
        "archive",
        "at_sign",
        "bar_chart_2",
        "battery_charging",
        "bell",
        "bluetooth",
        "book",
        "bookmark",
        "box",
        "calendar",
        "check_square",
        "chevron_down",
        "chevron_left",
        "chevron_right",
        "chevron_up",
        "clipboard",
        "clock",
        "code",
        "command",
        "compass",
        "copy",
        "crop",
        "crosshair",
        "delete",
        "download_cloud",
        "edit_2",
        "edit_3",
        "external_link",
        "eye_off",
        "facebook",
        "fast_forward",
        "file_minus",
        "file_plus",
        "file_text",
        "film_alt",
        "folder",
        "folder_minus",
        "folder_plus",
        "gift_alt",
        "github",
        "gitlab",
        "globe_alt",
        "grid_alt",
        "hard_drive_alt",
        "heart_alt",
        "help_circle",
        "home",
        "image",
        "inbox",
        "info",
        "instagram",
        "layout",
        "life_buoy",
        "linkedin",
        "loader",
        "log_in",
        "log_out",
        "mail",
        "map",
        "maximize_2",
        "menu",
        "message_circle",
        "message_square",
        "minimize_2",
        "monitor",
        "more_horizontal",
        "more_vertical",
        "move",
        "music",
        "navigation_2",
        "navigation",
        "octagon",
        "package_alt",
        "pause_circle",
        "percent",
        "phone_call",
        "phone_forwarded",
        "phone_incoming",
        "phone_missed",
        "phone_off",
        "phone_outgoing",
        "pie_chart",
        "play_circle",
        "plus_circle",
        "plus_square",
        "pocket",
        "power_off",
        "radio",
        "refresh_ccw",
        "refresh_cw",
        "repeat",
        "rewind",
        "rotate_ccw",
        "rotate_cw",
        "rss",
        "save_alt",
        "send",
        "settings_2",
        "share",
        "shopping_cart",
        "shuffle",
        "sidebar",
        "skip_back",
        "skip_forward",
        "slack",
        "sliders",
        "speaker_alt",
        "square",
        "stop_circle",
        "tablet",
        "tag_alt",
        "thumbs_down",
        "thumbs_up",
        "toggle_left",
        "toggle_right",
        "trash",
        "trending_down",
        "triangle",
        "twitter",
        "user_check",
        "user_minus",
        "user_plus",
        "user_x",
        "users",
        "video_off",
        "voicemail",
        "volume_1",
        "volume_x",
        "wifi_off",
        "youtube",
        "zap_off",
        "zoom_out",
        "alert_triangle",
        "align_center",
        "align_justify",
        "align_left",
        "align_right",
        "arrow_down_circle",
        "arrow_down_left",
        "arrow_down_right",
        "arrow_down",
        "arrow_left_circle",
        "arrow_left",
        "arrow_right_circle",
        "arrow_right",
        "arrow_up_circle",
        "arrow_up_left",
        "arrow_up_right",
        "arrow_up",
        "award_alt",
        "bold",
        "check_circle",
        "check",
        "chrome",
        "cloud_drizzle",
        "cloud_lightning",
        "cloud_off",
        "cloud_rain",
        "cloud_snow",
        "cloud",
        "codepen",
        "codesandbox",
        "credit_card",
        "crop_alt",
        "divide_circle",
        "divide_square",
        "divide",
        "dollar_sign_alt",
        "download",
        "droplet",
        "edit",
        "eye",
        "figma",
        "file",
        "folder_alt",
        "frown",
        "globe_2",
        "italic",
        "link_2",
        "list",
        "meh",
        "minus_circle",
        "minus_square",
        "minus",
        "moon_alt",
        "mouse_pointer_alt",
        "paperclip_alt",
        "pause",
        "pen_tool_alt",
        "play",
        "plus",
        "shield_off",
        "smile",
        "star_half",
        "sun_alt",
        "terminal",
        "underline",
        "upload",
        "x_circle",
        "x_octagon",
        "x_square",
        "x",
    ]

    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"


settings = AppSettings()